export const mockProducts = [
  {
    id: "mock-1",
    title: "Logitech MX Keys Wireless Keyboard",
    category: "mobile-accessories",
    brand: "Logitech",
    price: 99.99,
    rating: 4.7,
    stock: 18,
    discountPercentage: 0,
    description: "A wireless keyboard with comfortable typing, backlit keys, and long battery life.",
    thumbnail: "https://resource.logitech.com/w_692,c_lpad,ar_4:3,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/keyboards/mx-keys-for-business/gallery/mx-keys-business-keyboard-s-gallery-us-graphite-4.png?v=1",
  },
  {
    id: "mock-2",
    title: "Corsair K95 RGB Mechanical Keyboard",
    category: "mobile-accessories",
    brand: "Corsair",
    price: 159.99,
    rating: 4.5,
    stock: 10,
    discountPercentage: 0,
    description: "A mechanical gaming keyboard with customizable RGB lighting and dedicated macro keys.",
    thumbnail: "https://assets.corsair.com/image/upload/c_pad,q_auto,h_1024,w_1024,f_auto/products/Gaming-Keyboards/CH-9000222-NA/Gallery/CGK65_RGB_NA_08_B.webp",
  },
  {
    id: "mock-3",
    title: "Apple Magic Keyboard",
    category: "mobile-accessories",
    brand: "Apple",
    price: 129.99,
    rating: 4.4,
    stock: 25,
    discountPercentage: 0,
    description: "A sleek wireless keyboard designed for Mac, with a rechargeable battery.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKCYRqgb14xPw_IN1pALQ9o2RmTpCJzYk5D510IQLctR2qLVqj5shNnuay&s=10",
  },
  {
    id: "mock-4",
    title: "Keychron K2 Wireless Keyboard",
    category: "mobile-accessories",
    brand: "Keychron",
    price: 89.99,
    rating: 4.6,
    stock: 14,
    discountPercentage: 0,
    description: "A compact wireless mechanical keyboard with hot-swappable switches.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWE6BNV6KIUR6D909fx9UOb_bfTXqiYB1nsIHs1Mbk0yUW8e0Cjg7j71A&s=10",
  },
  {
    id: "mock-5",
    title: "Logitech G Pro Wireless Mouse",
    category: "mobile-accessories",
    brand: "Logitech",
    price: 79.99,
    rating: 4.6,
    stock: 20,
    discountPercentage: 0,
    description: "A lightweight wireless gaming mouse built for competitive esports players.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo7n6SENfQr9WjnF9Jt531-RTjdDYQOim3HbTn24-srw&s=10",
  },
  {
    id: "mock-6",
    title: "Razer DeathAdder Gaming Mouse",
    category: "mobile-accessories",
    brand: "Razer",
    price: 59.99,
    rating: 4.5,
    stock: 22,
    discountPercentage: 0,
    description: "An ergonomic gaming mouse with high-precision optical sensor.",
    thumbnail: "https://www.maxgaming.com/img/bilder/artiklar/21363.jpg?m=1648725082&w=720",
  },
  {
    id: "mock-7",
    title: "Apple Magic Mouse",
    category: "mobile-accessories",
    brand: "Apple",
    price: 99.99,
    rating: 4.2,
    stock: 16,
    discountPercentage: 0,
    description: "A rechargeable wireless mouse with a multi-touch surface.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4umKMq5XEZJoDmLo5M3H1AILGMf3MnNt1ihMMvC5YxA&s=10",
  },
  {
    id: "mock-8",
    title: "Microsoft Ergonomic Mouse",
    category: "mobile-accessories",
    brand: "Microsoft",
    price: 49.99,
    rating: 4.3,
    stock: 19,
    discountPercentage: 0,
    description: "A comfortable ergonomic mouse designed to reduce wrist strain.",
    thumbnail: "https://m.media-amazon.com/images/I/51gdLo9f9aL.jpg",
  },
  {
    id: "mock-9",
    title: "Sony WH-1000XM5 Headphone",
    category: "mobile-accessories",
    brand: "Sony",
    price: 349.99,
    rating: 4.8,
    stock: 9,
    discountPercentage: 0,
    description: "Industry-leading noise-cancelling headphones with premium sound quality.",
    thumbnail: "https://d1ncau8tqf99kp.cloudfront.net/converted/103364_original_local_504x441_v3_converted.webp",
  },
  {
    id: "mock-10",
    title: "JBL Tune 760NC Headphone",
    category: "mobile-accessories",
    brand: "JBL",
    price: 129.99,
    rating: 4.3,
    stock: 13,
    discountPercentage: 0,
    description: "Wireless over-ear headphones with active noise cancellation.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT13sEf4G8BFPctN0Cyf_dWOVrRw6iXDzjKX2B_nI-pA&s=10",
  },
  {
    id: "mock-11",
    title: "Bose QuietComfort Earbuds",
    category: "mobile-accessories",
    brand: "Bose",
    price: 279.99,
    rating: 4.6,
    stock: 11,
    discountPercentage: 0,
    description: "True wireless earbuds with best-in-class noise cancellation.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfcgGMMbP1g63JSBsFjp3AA5P71nlRK--QZY9XvNOnAQ&s=10",
  },
  {
    id: "mock-12",
    title: "Samsung Galaxy Buds Pro",
    category: "mobile-accessories",
    brand: "Samsung",
    price: 199.99,
    rating: 4.4,
    stock: 17,
    discountPercentage: 0,
    description: "Compact wireless earbuds with intelligent active noise cancellation.",
    thumbnail: "https://dkstatics-public.digikala.com/digikala-products/dc9e3c1a150747f0fe9b3133e724de1205495842_1695126607.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/quality,q_90",
  },
  {
    id: "mock-13",
    title: "Anker USB-C Fast Charging Cable",
    category: "mobile-accessories",
    brand: "Anker",
    price: 19.99,
    rating: 4.5,
    stock: 40,
    discountPercentage: 0,
    description: "A durable braided USB-C cable that supports fast charging.",
    thumbnail: "https://m.media-amazon.com/images/I/814oBlXCN8L._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: "mock-14",
    title: "Belkin Lightning Charging Cable",
    category: "mobile-accessories",
    brand: "Belkin",
    price: 24.99,
    rating: 4.4,
    stock: 35,
    discountPercentage: 0,
    description: "An MFi-certified Lightning cable built for reliable daily charging.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJogp6LaePkFhO7NemF-uvI-2Fvx69bTY0cFB0gZd8AbKe19RFky17QR4&s=10",
  },
  {
    id: "mock-15",
    title: "Samsung 45W Fast Charger",
    category: "mobile-accessories",
    brand: "Samsung",
    price: 34.99,
    rating: 4.6,
    stock: 28,
    discountPercentage: 0,
    description: "A compact wall charger that delivers fast charging up to 45W.",
    thumbnail: "https://dkstatics-public.digikala.com/digikala-products/fde6cdb74c3f7cc88c2e572dae324b68b4720fde_1652528274.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/quality,q_90",
  },
  {
    id: "mock-16",
    title: "Anker PowerLine USB-C Cable",
    category: "mobile-accessories",
    brand: "Anker",
    price: 15.99,
    rating: 4.3,
    stock: 45,
    discountPercentage: 0,
    description: "A reinforced USB-C cable built to withstand thousands of bends.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbtMt9l0EEn4MLGvzuHj6NrEt131t8g7pgsvhixJynVg&s=10",
  },
  {
    id: "mock-17",
    title: "Logitech K380 Multi-Device Keyboard",
    category: "mobile-accessories",
    brand: "Logitech",
    price: 39.99,
    rating: 4.5,
    stock: 21,
    discountPercentage: 0,
    description: "A compact Bluetooth keyboard that connects to up to three devices.",
    thumbnail: "https://shop1401.com/9406-large_default/logitech-k380-multi-device-bluetooth-keyboard.jpg",
  },
  {
    id: "mock-18",
    title: "Razer Basilisk Wireless Mouse",
    category: "mobile-accessories",
    brand: "Razer",
    price: 69.99,
    rating: 4.4,
    stock: 12,
    discountPercentage: 0,
    description: "A wireless gaming mouse with customizable weight and side controls.",
    thumbnail: "https://m.media-amazon.com/images/I/714EV8-LsXL.jpg",
  },
  {
    id: "mock-19",
    title: "Sennheiser Momentum Headphone",
    category: "mobile-accessories",
    brand: "Sennheiser",
    price: 299.99,
    rating: 4.7,
    stock: 7,
    discountPercentage: 0,
    description: "Premium over-ear headphones with rich, detailed sound.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8odZYX_jEC1NfH7IpSx89_O5SUO_-ySzC6sp5pM1s6g&s=10",
  },
  {
    id: "mock-20",
    title: "Belkin 20W USB-C Charger",
    category: "mobile-accessories",
    brand: "Belkin",
    price: 22.99,
    rating: 4.2,
    stock: 30,
    discountPercentage: 0,
    description: "A compact wall charger delivering fast, safe charging for phones.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf9V15sEOdgCJGR2YEuXR4WoZeQ56T7qpoTfmLMYzJ0jkjX7rSSzToUmKy&s=10",
  },
];